---
- name: Configure Elasticsearch service
  template:
    src: "{{ item.1 }}"
    dest: "{{ item.0 }}/{{ item.1 }}"  #/etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ templl }}"
  with_items: "{{ templl1 }}"
  # notify: Restart Elasticsearch

- name: Configure Elastic jvm
  template:
    src: jvm.options.j2
    dest: "{{ item }}"  
    owner: elasticsearch
    group: elasticsearch
    mode: '0644'
  with_items: "{{ templs }}"
  notify: Restart Elasticsearch






- name: Give insecure permissions to an existing file
  ansible.builtin.file:
    path: "{{ item }}"        #/etc/elasticsearch/elasticsearch.yml 
    owner: root
#     group: root
#     mode: '0777'
#   with_items: "{{ paths }}"
