---
- name: Configure service
  template:
    src: "{{ item }}"
    dest: /etc/scylla  #/etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ templl }}"
  # notify: Restart Elasticsearch

- name: Configure scylla cassandra
  template:
    src: "{{ item }}"
    dest: /etc/scylla/cassandra
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ templs }}"
  notify: Restart scylla






# - name: Give insecure permissions to an existing file
#   ansible.builtin.file:
#     path: "{{ item }}"        #/etc/elasticsearch/elasticsearch.yml 
#     owner: root
# #     group: root
# #     mode: '0777'
# #   with_items: "{{ paths }}"
