---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Import ScyllaDB GPG Key
  command: "{{ scylla_gpg }}"
  become: yes

- name: Add ScyllaDB Repository
  get_url:
    url: "{{ scylla_repo }}"
    dest: "{{ scylla_repo_dest }}"
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes

# - name: Install scylla
#   apt:
#     name: scylla
#     state: present
# - name: Start ScyllaDB Service
#   systemd:
#      name: scylla-server
#      state: started
- name: Wait for seconds
  pause:
    seconds: 5
