---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Import ScyllaDB GPG Key
  command: "{{ scylla_gpg }}"
  become: yes

- name: Add Elasticsearch repository
  apt_repository:
    repo: "{{ scylla_repo }}"
    state: present


- name: Add ScyllaDB Repository
  get_url:
    url: "{{ scylla_repo }}"
    dest: "{{ scylla_repo_dest }}"
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes

- name: Enable ScyllaDB Server service
  systemd:
    name: scylla-server
    enabled: yes
  notify:
    - Reload systemd

# - name: Install scylla
#   apt:
#     name: scylla
#     state: present
# - name: Start ScyllaDB Service
#   systemd:
#      name: scylla-server
#      state: started
