---

- name: directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0777"
  become: true

- name: Update apt cache
  apt:
    update_cache: yes

- name: Import ScyllaDB GPG Key
  command: "{{ scylla_gpg }}"
  become: yes

- name: Add ScyllaDB Repository
  get_url:
    url: "{{ scylla_repo }}"
    dest: "{{ scylla_repo_dest }}"
  become: yes





#- name: Add ScyllaDB Repository
#  command: "{{ scylla_repo }}"
#  become: yes

#- name: Import ScyllaDB GPG Key
#  command: sudo gpg --homedir /tmp --no-default-keyring --keyring /etc/apt/keyrings/scylladb.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys d0a112e067426ab2

#- name: Add ScyllaDB Repository
#  command: sudo wget -O /etc/apt/sources.list.d/scylla.list http://downloads.scylladb.com/deb/debian/scylla-5.2.list

#- name: Add ScyllaDB GPG key
 # command: "{{ archive.key }}"      

#- name: Add ScyllaDB repository
#  command: "{{ repo }}"


# - name: Install ScyllaDB
#   apt:
#     name: scylla
#     state: present
#   notify: Start ScyllaDB

# - name: Start ScyllaDB
#   systemd:
#     name: scylla-server
#     enabled: yes
#     state: started
